log:
  stdout_log_level: INFO
  log_file_level: DEBUG
  log_file: platform_service.log

!include shared_config.yaml

apps:
  - name: platform_service_app
    app_base_path: .
    app_module: solace_agent_mesh.services.platform.app

    broker:
      <<: *broker_connection

    app_config:
      namespace: ${NAMESPACE}
      database_url: ${PLATFORM_DATABASE_URL}
      fastapi_host: ${PLATFORM_API_HOST, 0.0.0.0}
      fastapi_port: ${PLATFORM_API_PORT, 8001}
      frontend_use_authorization: ${USE_AUTHORIZATION, false}
      max_message_size_bytes: ${MAX_MESSAGE_SIZE_BYTES, 10000000}
      cors_allowed_origins:
        - "${FRONTEND_SERVER_URL}"
        - "http://localhost:3000"
        - "http://127.0.0.1:3000"
        - "http://localhost:8000"
      cors_allowed_origin_regex: ${CORS_ALLOWED_ORIGIN_REGEX}
