#!/usr/bin/env bash
set -euo pipefail

# bootstrap-env.sh - Generate .env files from envs/ templates
#
# Usage:
#   ./scripts/bootstrap-env.sh [environment] [llm-profile]
#
# Arguments:
#   environment  - Address/infra profile (e.g., dev, prod). Default: "default"
#   llm-profile  - LLM service profile (e.g., public, air-gapped). Default: "default"
#
# When invoked without arguments, uses "default" for both. The default profiles
# are symlinks: envs/overrides/default.env -> dev.env, envs/llm/default.env -> public.env.
# Change the symlink targets to switch your default configuration.
#
# This script merges environment variable templates from envs/ into:
#   1. .env              (root, for Docker Compose)
#   2. curr-proj/.env    (SAM runtime inside container)
#   3. curr-proj/agent.env (deployed agent containers via DinD)
#
# Merge order (later files override earlier ones):
#   common.env -> llm/<profile>.env -> layer-specific.env -> overrides/<env>.env

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENVS_DIR="$PROJECT_ROOT/envs"

ENV_NAME="${1:-default}"
LLM_PROFILE="${2:-default}"

show_usage() {
    echo "Usage: $0 [environment] [llm-profile]"
    echo ""
    echo "Both arguments are optional. Defaults to 'default' for each."
    echo ""
    echo "Available environments:"
    for f in "$ENVS_DIR/overrides/"*.env; do
        local name
        name="$(basename "$f" .env)"
        if [ -L "$f" ]; then
            local target
            target="$(basename "$(readlink "$f")" .env)"
            echo "  $name -> $target"
        else
            echo "  $name"
        fi
    done
    echo ""
    echo "Available LLM profiles:"
    for f in "$ENVS_DIR/llm/"*.env; do
        local name
        name="$(basename "$f" .env)"
        if [ -L "$f" ]; then
            local target
            target="$(basename "$(readlink "$f")" .env)"
            echo "  $name -> $target"
        else
            echo "  $name"
        fi
    done
}

OVERRIDE_FILE="$ENVS_DIR/overrides/${ENV_NAME}.env"
if [ ! -f "$OVERRIDE_FILE" ]; then
    echo "Error: environment override not found: $OVERRIDE_FILE"
    echo ""
    show_usage
    exit 1
fi

LLM_FILE="$ENVS_DIR/llm/${LLM_PROFILE}.env"
if [ ! -f "$LLM_FILE" ]; then
    echo "Error: LLM profile not found: $LLM_FILE"
    echo ""
    show_usage
    exit 1
fi

# merge_env_files: merge multiple .env files, later files override earlier ones.
# Strips comments and blank lines, keeps last occurrence of each variable.
merge_env_files() {
    local output_file="$1"
    shift
    local tmp
    tmp=$(mktemp)

    for src in "$@"; do
        if [ -f "$src" ]; then
            # Strip comments and blank lines, append to temp
            grep -v '^\s*#' "$src" | grep -v '^\s*$' >> "$tmp" || true
        fi
    done

    # Deduplicate: keep last occurrence of each KEY=value
    local result
    result=$(mktemp)
    tac "$tmp" | awk -F= '!seen[$1]++' | tac > "$result"

    # Write with header
    {
        echo "# AUTO-GENERATED by bootstrap-env.sh (env: ${ENV_NAME}, llm: ${LLM_PROFILE})"
        echo "# Do not edit directly. Modify files in envs/ and re-run the script."
        echo "# Generated at: $(date -Iseconds)"
        echo ""
        cat "$result"
    } > "$output_file"

    rm -f "$tmp" "$result"
}

# For agent.env, we need to translate AGENT_BROKER_URL -> SOLACE_BROKER_URL etc.
# This function takes merged output and replaces address variables for agents.
apply_agent_address_overrides() {
    local file="$1"
    local tmp
    tmp=$(mktemp)

    # Read AGENT_* values from the file
    local agent_broker_url agent_s3_endpoint
    agent_broker_url=$(grep '^AGENT_BROKER_URL=' "$file" 2>/dev/null | tail -1 | cut -d= -f2- || true)
    agent_s3_endpoint=$(grep '^AGENT_S3_ENDPOINT_URL=' "$file" 2>/dev/null | tail -1 | cut -d= -f2- || true)

    # Replace the SAM-facing URLs with agent-facing URLs
    while IFS= read -r line; do
        if [ -n "$agent_broker_url" ] && echo "$line" | grep -q '^SOLACE_BROKER_URL='; then
            echo "SOLACE_BROKER_URL=$agent_broker_url"
        elif [ -n "$agent_s3_endpoint" ] && echo "$line" | grep -q '^S3_ENDPOINT_URL='; then
            echo "S3_ENDPOINT_URL=$agent_s3_endpoint"
        elif echo "$line" | grep -q '^AGENT_'; then
            # Strip AGENT_* variables from output (they are internal to bootstrap)
            continue
        else
            echo "$line"
        fi
    done < "$file" > "$tmp"

    mv "$tmp" "$file"
}

echo "Bootstrapping environment: ${ENV_NAME}, LLM profile: ${LLM_PROFILE}"
echo ""

# --- Generate root .env (Layer 1: Docker Compose) ---
ROOT_ENV="$PROJECT_ROOT/.env"
merge_env_files "$ROOT_ENV" \
    "$ENVS_DIR/common.env" \
    "$LLM_FILE" \
    "$ENVS_DIR/compose.env" \
    "$OVERRIDE_FILE"

# Remove AGENT_* lines from root env (not needed by Docker Compose)
grep -v '^AGENT_' "$ROOT_ENV" > "${ROOT_ENV}.tmp" && mv "${ROOT_ENV}.tmp" "$ROOT_ENV"

echo "Generated: .env"

# --- Generate curr-proj/.env (Layer 2: SAM Runtime) ---
CURR_PROJ_DIR="$PROJECT_ROOT/curr-proj"
if [ ! -d "$CURR_PROJ_DIR" ]; then
    echo "Warning: curr-proj/ directory not found. Skipping curr-proj/.env generation."
else
    SAM_ENV="$CURR_PROJ_DIR/.env"
    merge_env_files "$SAM_ENV" \
        "$ENVS_DIR/common.env" \
        "$LLM_FILE" \
        "$ENVS_DIR/sam.env" \
        "$OVERRIDE_FILE"

    # Remove AGENT_* lines from SAM env (not needed)
    grep -v '^AGENT_' "$SAM_ENV" > "${SAM_ENV}.tmp" && mv "${SAM_ENV}.tmp" "$SAM_ENV"

    echo "Generated: curr-proj/.env"
fi

# --- Generate curr-proj/agent.env (Layer 3: Deployed Agents) ---
if [ ! -d "$CURR_PROJ_DIR" ]; then
    echo "Warning: curr-proj/ directory not found. Skipping curr-proj/agent.env generation."
else
    AGENT_ENV="$CURR_PROJ_DIR/agent.env"
    merge_env_files "$AGENT_ENV" \
        "$ENVS_DIR/common.env" \
        "$LLM_FILE" \
        "$ENVS_DIR/agent.env" \
        "$OVERRIDE_FILE"

    # Apply AGENT_* address overrides (AGENT_BROKER_URL -> SOLACE_BROKER_URL)
    apply_agent_address_overrides "$AGENT_ENV"

    echo "Generated: curr-proj/agent.env"
fi

echo ""
echo "Done. Environment '${ENV_NAME}' with LLM profile '${LLM_PROFILE}' has been applied."
echo "Review the generated files before starting services."
